spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    password: Narendra_01
    username: system
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8090